#!/bin/sh
# shellcheck disable=SC1091,SC2039
# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 :

. /lib/functions.sh

#if image creates wan6 we need to delete it.
[ "$(uci -q get "network.wan6")" = 'interface' ] && \
	uci -q batch <<-EOF
	delete network.wan6 
	EOF

#image creates a default wan. We need to reconfigure it.    
[ "$(uci -q get "network.wan")" = 'interface' ] && \
	uci -q batch <<-EOF
	delete network.wan.device
	set network.wan.ifname=eth1
	rename network.wan=wan1
	EOF

#delete br-lan bridge from lan configuration.
[ "$(uci -q get "network.lan.device")" = 'br-lan' ] && \
	uci -q batch <<-EOF
	delete network.lan.device
	EOF

#we do not need br-lan pre-configured.
[ "$(uci -q get "network.@device[0]")" = 'device' ] && \
	uci -q batch <<-EOF
	delete network.@device[0]
	EOF
	
	